export const ORDEN_EQUIPOS = [
  "Deportivo Alavés",
  "Athletic Club",
  "Atlético de Madrid",
  "Fútbol Club Barcelona",
  "Real Betis Balompié",
  "Real Club Celta de Vigo",
  "Real Club Deportivo de A Coruña",
  "Elche Club de Fútbol",
  "Real Club Deportivo Espanyol de Barcelona",
  "Getafe Club de Fútbol",
  "Levante Unión Deportiva",
  "Málaga Club de Fútbol",
  "Club Atlético Osasuna",
  "Real Racing Club de Santander",
  "Rayo Vallecano de Madrid",
  "Real Madrid",
  "Real Sociedad de Fútbol",
  "Sevilla Fútbol Club",
  "Valencia Club de Fútbol",
  "Villarreal Club de Fútbol",
];
